version: '2'
services:
    springboot_jhipster-app:
        image: springboot_jhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://springboot_jhipster-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=springboot_jhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    springboot_jhipster-mongodb:
        extends:
            file: mongodb.yml
            service: springboot_jhipster-mongodb
